name: Crypto Futures Checker

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [run-bot]
# جلوگیری از تداخل اجراها (اگر اکشن قبلی طول کشید، این یکی صبر کند یا اون رو لغو کند)
concurrency:
  group: fvg-scan-group
  cancel-in-progress: true

jobs:
  check-prices:
    runs-on: ubuntu-latest
    timeout-minutes: 3   # اگر کد بیشتر از 3 دقیقه طول کشید، گیت‌هاب آن را متوقف کند تا رایگان بماند

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Bot Script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: python spike_detector.py
